base_url = "https://dkurkin.dev"
theme = "zola-theme-kurkin"
compile_sass = false
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
accent_color = "blue"
background_color = "light"