name: dkurkin.dev CI
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache Zola Installation
        uses: actions/cache@v4
        id: cache-zola
        with:
          path: /usr/local/bin/zola
          key: ${{ runner.os }}-zola
      - name: Download and Install Zola
        if: steps.cache-zola.outputs.cache-hit != 'true'
        run: curl --location https://github.com/getzola/zola/releases/download/v0.18.0/zola-v0.18.0-x86_64-unknown-linux-gnu.tar.gz | tar xvzf - -C /usr/local/bin
      - name: Build Zola Site
        run: zola build
      - name: Upload Built Static Files
        uses: actions/upload-artifact@v4
        with:
          name: site-static-files
          path: |
            public
            scripts
  deploy:
    runs-on: ubuntu-22.04
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Download Built Static Files
        uses: actions/download-artifact@v4
        with:
          name: site-static-files
      - name: Clean S3 bucket
        run: sh ./scripts/clean-bucket.sh
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_OUTPUT: json
      - name: Upload to S3 bucket
        run: sh ./scripts/upload-bucket.sh
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_OUTPUT: json
      - name: Invalidate CloudFront distribution
        run: aws cloudfront create-invalidation --distribution-id=${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths='/*'
        env:
          AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_OUTPUT: json